name: CMake Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: run build (unix)
        shell: bash
        run: ./build.sh --clean
        if: runner.os != 'Windows'

      - name: run build (windows)
        shell: pwsh
        run: .\build.ps1 -Clean
        if: runner.os == 'Windows'

      - name: print build output
        shell: bash
        run: ls -al ./build/ && echo "" echo ls -al ./build/*
