name: CMake Build

on:
  push:
    branches:
      - master

jobs:
  build-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      vst-artifact: ${{ steps.artifact-upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: run build (unix)
        shell: bash
        run: ./build.sh --clean --type release

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: "capacitor2tweak-${{ matrix.os }}"
          path: ./build/VST3/Release/
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    outputs:
      vst-artifact: ${{ steps.artifact-upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: run build (windows)
        shell: pwsh
        run: .\build.ps1 -Clean -Type Release

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: "capacitor2tweak-windows"
          path: ./build/VST3/Release/Capacitor2Tweak.vst3/Contents/x86_64-win/
          if-no-files-found: error
