name: CMake Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check-ssh
        shell: bash
        run: ssh -vT git@github.com
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: check-submodules
        shell: bash
        run: ls -al ./include/vst3sdk/cmake
      - name: build
        shell: bash
        run: ./build.sh --clean
