name: CMake Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      vst-artifact: ${{ steps.artifact-upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: run build (unix)
        shell: bash
        run: ./build.sh --clean --type release
        if: runner.os != 'Windows'

      - name: run build (windows)
        shell: pwsh
        run: .\build.ps1 -Clean -Type Release
        if: runner.os == 'Windows'

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: "capacitor2fix-${{ matrix.os }}"
          path: ./build/VST3/Release/
          if-no-files-found: error
